development:
  adapter: postgresql
  encoding: utf8
  database: cheese_dev
  pool: 5
  username: robanderson
  password: 

test:
  adapter: postgresql
  encoding: utf8
  database: cheese_test
  pool: 5
  username: robanderson
  password: 

production:
  adapter: postgresql
  encoding: utf8
  database: cheese
  username: robanderson
  password: 
  pool: 5
  timeout: 5000 
